-- AquaShield AI Database Schema

-- 1. Sensor Readings Table (Stores IoT/API Data)
CREATE TABLE public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    station_id TEXT DEFAULT 'STATION_001', -- For multiple sensors in future
    rainfall FLOAT DEFAULT 0,              -- Real-time rainfall (mm)
    water_level FLOAT DEFAULT 0,           -- Measured water level (m)
    soil_moisture FLOAT DEFAULT 0,         -- From AI Model (0-100)
    api_index FLOAT DEFAULT 0              -- Antecedent Precipitation Index
);

-- 2. Alerts Table (Stores Alert History)
CREATE TABLE public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    level TEXT CHECK (level IN ('LOW', 'MEDIUM', 'HIGH')),
    message TEXT,
    location TEXT
);

-- 3. API Logs (Already used, ensuring existence)
CREATE TABLE IF NOT EXISTS public.api_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    source TEXT,
    data JSONB
);

-- Enable Row Level Security (RLS) - Optional for prototype but good practice
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_logs ENABLE ROW LEVEL SECURITY;

-- Allow Anon Read/Write for Prototype (Simulating IoT Device)
CREATE POLICY "Allow Anon All" ON public.sensor_readings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Anon All" ON public.alerts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Anon All" ON public.api_logs FOR ALL USING (true) WITH CHECK (true);
